#!/usr/local/bin/zsh

function semicolon {
    function start_vim {
        if [ -z "$TMUX" ]; then
            tmux new "vim --servername $1"
        else
            vim --servername $1 
        fi
    }

    local ORIG_DIR=$(pwd)

    if [ -n "$VIRTUAL_ENV" ]; then
        local ORIG_ENV=$(basename $VIRTUAL_ENV)
    fi

    if [ "$#" -eq 1 ]; then
        workon $1
        start_vim $1
        deactivate
    else
        start_vim VIM
    fi


    if [ -n "$ORIG_ENV" ]; then
        workon $ORIG_ENV
    fi

    cd $ORIG_DIR
}

if hash workon 2>/dev/null; then
    compctl -k "( $(workon) )" semicolon
fi
